import { CandlestickPattern } from '../types/index.js';

export const DEFAULT_PATTERNS: CandlestickPattern[] = [
  // --- NẾN ĐƠN (SINGLE) ---
  {
    id: 'pattern-hammer',
    name: 'Hammer (Nến Búa)',
    category: 'SINGLE',
    signal: 'BUY',
    candleCount: 1,
    description: 'Râu nến dưới dài gấp ít nhất 2 lần thân nến, râu trên rất nhỏ hoặc không có. Tín hiệu đảo chiều tăng giá mạnh ở đáy.',
    candles: [
      {
        position: 1,
        label: 'Nến Búa',
        direction: 'ANY',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 35 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 2.0 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-shooting-star',
    name: 'Shooting Star (Sao Băng)',
    category: 'SINGLE',
    signal: 'SELL',
    candleCount: 1,
    description: 'Râu nến trên dài gấp ít nhất 2 lần thân nến, râu dưới rất nhỏ. Báo hiệu lực từ chối giá đỉnh, đảo chiều giảm.',
    candles: [
      {
        position: 1,
        label: 'Nến Sao Băng',
        direction: 'ANY',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 35 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 2.0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-inverted-hammer',
    name: 'Inverted Hammer (Búa Ngược)',
    category: 'SINGLE',
    signal: 'BUY',
    candleCount: 1,
    description: 'Xuất hiện ở đáy xu hướng giảm, râu trên dài gấp 2 lần thân nến. Phe Mua bắt đầu xuất hiện đẩy giá lên.',
    candles: [
      {
        position: 1,
        label: 'Nến Búa Ngược',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 40 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 2.0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-hanging-man',
    name: 'Hanging Man (Người Treo Cổ)',
    category: 'SINGLE',
    signal: 'SELL',
    candleCount: 1,
    description: 'Xuất hiện ở đỉnh xu hướng tăng, râu dưới dài gấp 2 lần thân. Phe Bán đã bắt đầu thử nghiệm lực đẩy giá xuống.',
    candles: [
      {
        position: 1,
        label: 'Nến Người Treo Cổ',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 35 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.2 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 2.0 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-dragonfly-doji',
    name: 'Dragonfly Doji (Chuồn Chuồn)',
    category: 'SINGLE',
    signal: 'BUY',
    candleCount: 1,
    description: 'Giá mở cửa và đóng cửa xấp xỉ mức đỉnh, râu dưới siêu dài. Tín hiệu đảo chiều tăng giá rất nhạy.',
    candles: [
      {
        position: 1,
        label: 'Doji Chuồn Chuồn',
        direction: 'DOJI',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 8 },
        upperWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 5 },
        lowerWick: { mode: 'PERCENT_OF_RANGE', operator: '>=', value: 75 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-gravestone-doji',
    name: 'Gravestone Doji (Bia Mộ)',
    category: 'SINGLE',
    signal: 'SELL',
    candleCount: 1,
    description: 'Giá mở cửa và đóng cửa xấp xỉ mức đáy, râu trên siêu dài. Tín hiệu đảo chiều giảm giá cực nhạy.',
    candles: [
      {
        position: 1,
        label: 'Doji Bia Mộ',
        direction: 'DOJI',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 8 },
        upperWick: { mode: 'PERCENT_OF_RANGE', operator: '>=', value: 75 },
        lowerWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 5 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-bullish-marubozu',
    name: 'Bullish Marubozu (Cường Lực Tăng)',
    category: 'SINGLE',
    signal: 'BUY',
    candleCount: 1,
    description: 'Thân nến xanh chiếm trọn trên 85% chiều dài nến, hầu như không có râu. Phe Mua áp đảo toàn diện.',
    candles: [
      {
        position: 1,
        label: 'Marubozu Xanh',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 85 },
        upperWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 8 },
        lowerWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 8 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-bearish-marubozu',
    name: 'Bearish Marubozu (Cường Lực Giảm)',
    category: 'SINGLE',
    signal: 'SELL',
    candleCount: 1,
    description: 'Thân nến đỏ chiếm trọn trên 85% chiều dài nến, hầu như không có râu. Phe Bán áp đảo toàn diện.',
    candles: [
      {
        position: 1,
        label: 'Marubozu Đỏ',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 85 },
        upperWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 8 },
        lowerWick: { mode: 'PERCENT_OF_RANGE', operator: '<=', value: 8 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },

  // --- NẾN ĐÔI (DOUBLE) ---
  {
    id: 'pattern-bullish-engulfing',
    name: 'Bullish Engulfing (Nhấn Chìm Tăng)',
    category: 'DOUBLE',
    signal: 'BUY',
    candleCount: 2,
    description: 'Nến 1 giảm, nến 2 tăng mạnh có thân to bao trùm hoàn toàn thân nến 1 (thân nến 2 >= 120% thân nến 1).',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Giảm',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Nhấn chìm tăng',
        direction: 'BULLISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_BODY', operator: '>=', value: 120 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.5 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.5 },
        relative: { engulfsPrevious: true, closeAbovePreviousOpen: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-bearish-engulfing',
    name: 'Bearish Engulfing (Nhấn Chìm Giảm)',
    category: 'DOUBLE',
    signal: 'SELL',
    candleCount: 2,
    description: 'Nến 1 tăng, nến 2 giảm mạnh có thân to bao trùm hoàn toàn thân nến 1 (thân nến 2 >= 120% thân nến 1).',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Tăng',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Nhấn chìm giảm',
        direction: 'BEARISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_BODY', operator: '>=', value: 120 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.5 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.5 },
        relative: { engulfsPrevious: true, closeBelowPreviousOpen: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-tweezer-bottom',
    name: 'Tweezer Bottom (Đáy Nhíp)',
    category: 'DOUBLE',
    signal: 'BUY',
    candleCount: 2,
    description: '2 nến liên tiếp có cùng đáy (râu dưới nến 2 xấp xỉ râu dưới nến 1 trong khoảng 90% - 110%). Hỗ trợ kép bật tăng.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Giảm chạm đáy',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 0.8 },
      },
      {
        position: 2,
        label: 'Nến 2: Bật đáy nhíp',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'PERCENT_OF_PREVIOUS_LOWER', operator: '>=', value: 90 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-tweezer-top',
    name: 'Tweezer Top (Đỉnh Nhíp)',
    category: 'DOUBLE',
    signal: 'SELL',
    candleCount: 2,
    description: '2 nến liên tiếp có cùng đỉnh (râu trên nến 2 xấp xỉ râu trên nến 1 trong khoảng 90% - 110%). Kháng cự kép quay đầu giảm.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Tăng chạm đỉnh',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '>=', value: 0.8 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Giảm đỉnh nhíp',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'PERCENT_OF_PREVIOUS_UPPER', operator: '>=', value: 90 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-bullish-harami',
    name: 'Bullish Harami (Mẹ Bồng Con Tăng)',
    category: 'DOUBLE',
    signal: 'BUY',
    candleCount: 2,
    description: 'Nến 1 giảm dài, nến 2 xanh nhỏ nằm gọn lọt bên trong thân nến 1 (thân nến 2 <= 50% thân nến 1). Nén lực bứt phá tăng.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Nến Mẹ (Giảm lớn)',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 60 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Nến Con (Xanh nhỏ)',
        direction: 'BULLISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_BODY', operator: '<=', value: 50 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
        relative: { insidePreviousBar: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },

  // --- NẾN BA (TRIPLE) ---
  {
    id: 'pattern-morning-star',
    name: 'Morning Star (Sao Mai Đảo Chiều)',
    category: 'TRIPLE',
    signal: 'BUY',
    candleCount: 3,
    description: 'Nến 1 giảm mạnh, nến 2 là nến nhỏ giằng co ở đáy, nến 3 tăng mạnh đóng cửa vượt quá 50% thân nến 1.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Giảm mạnh',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 60 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Nến Ngôi Sao (Đáy)',
        direction: 'ANY',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 30 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 3,
        label: 'Nến 3: Tăng xác nhận',
        direction: 'BULLISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_TOTAL', operator: '>=', value: 70 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-evening-star',
    name: 'Evening Star (Sao Hôm Đảo Chiều)',
    category: 'TRIPLE',
    signal: 'SELL',
    candleCount: 3,
    description: 'Nến 1 tăng mạnh, nến 2 là nến nhỏ giằng co ở đỉnh, nến 3 giảm mạnh đâm sâu vào thân nến 1.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Tăng mạnh',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 60 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Nến Ngôi Sao (Đỉnh)',
        direction: 'ANY',
        body: { mode: 'RATIO_TO_RANGE', operator: '<=', value: 30 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 3,
        label: 'Nến 3: Giảm xác nhận',
        direction: 'BEARISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_TOTAL', operator: '>=', value: 70 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-three-white-soldiers',
    name: 'Three White Soldiers (3 Chàng Lính Trắng)',
    category: 'TRIPLE',
    signal: 'BUY',
    candleCount: 3,
    description: '3 nến xanh liên tiếp có thân dài, nến sau mở cửa trong thân nến trước và đóng cửa tạo đỉnh cao mới. Lực mua cuồn cuộn.',
    candles: [
      {
        position: 1,
        label: 'Lính 1',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Lính 2',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
        relative: { higherHigh: true },
      },
      {
        position: 3,
        label: 'Lính 3',
        direction: 'BULLISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
        relative: { higherHigh: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-three-black-crows',
    name: 'Three Black Crows (3 Con Quạ Đen)',
    category: 'TRIPLE',
    signal: 'SELL',
    candleCount: 3,
    description: '3 nến đỏ liên tiếp có thân dài, nến sau mở cửa trong thân nến trước và đóng cửa tạo đáy thấp mới. Lực xả bán tháo cực mạnh.',
    candles: [
      {
        position: 1,
        label: 'Quạ 1',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
      },
      {
        position: 2,
        label: 'Quạ 2',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
        relative: { lowerLow: true },
      },
      {
        position: 3,
        label: 'Quạ 3',
        direction: 'BEARISH',
        body: { mode: 'RATIO_TO_RANGE', operator: '>=', value: 65 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.4 },
        relative: { lowerLow: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },

  // --- NẾN BỐN / ĐA NẾN (MULTI) ---
  {
    id: 'pattern-bullish-three-line-strike',
    name: 'Bullish Three Line Strike (4 Nến Đột Phá)',
    category: 'MULTI',
    signal: 'BUY',
    candleCount: 4,
    description: '3 nến đỏ giảm liên tiếp, theo sau bởi 1 nến xanh khổng lồ nuốt chửng toàn bộ 3 cây nến đỏ trước đó. Tín hiệu đảo chiều kinh điển.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Đỏ',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Đỏ',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 3,
        label: 'Nến 3: Đỏ',
        direction: 'BEARISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 4,
        label: 'Nến 4: Xanh đại thụ nuốt 3 nến trước',
        direction: 'BULLISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_BODY', operator: '>=', value: 200 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
        relative: { higherHigh: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'pattern-bearish-three-line-strike',
    name: 'Bearish Three Line Strike (4 Nến Đảo Chiều Giảm)',
    category: 'MULTI',
    signal: 'SELL',
    candleCount: 4,
    description: '3 nến xanh tăng liên tiếp, theo sau bởi 1 nến đỏ khổng lồ nuốt chửng toàn bộ 3 cây nến xanh trước đó. Tín hiệu xả đỉnh cực mạnh.',
    candles: [
      {
        position: 1,
        label: 'Nến 1: Xanh',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 2,
        label: 'Nến 2: Xanh',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 3,
        label: 'Nến 3: Xanh',
        direction: 'BULLISH',
        body: { mode: 'ANY', operator: '>=', value: 0 },
        upperWick: { mode: 'ANY', operator: '>=', value: 0 },
        lowerWick: { mode: 'ANY', operator: '>=', value: 0 },
      },
      {
        position: 4,
        label: 'Nến 4: Đỏ khổng lồ nuốt 3 nến trước',
        direction: 'BEARISH',
        body: { mode: 'PERCENT_OF_PREVIOUS_BODY', operator: '>=', value: 200 },
        upperWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
        lowerWick: { mode: 'RATIO_TO_BODY', operator: '<=', value: 0.3 },
        relative: { lowerLow: true },
      }
    ],
    isActive: true,
    isPredefined: true,
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  }
];
